In [4]:
import pandas as pd
data = {
    'employee_id': [101, 102, 103, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'age': [28, 34, 29, 40, 24, 30],
    'department': ['HR', 'Finance', 'IT', 'Marketing', 'Sales', 'IT'],
    'salary': [70000, 80000, 75000, 90000, 65000, 72000]
}

df=pd.DataFrame(data)
df

   employee_id     name  age department  salary
0          101    Alice   28         HR   70000
1          102      Bob   34    Finance   80000
2          103  Charlie   29         IT   75000
3          104    David   40  Marketing   90000
4          105      Eva   24      Sales   65000
5          106    Frank   30         IT   72000

In [6]:
df.head(3)

   employee_id     name  age department  salary
0          101    Alice   28         HR   70000
1          102      Bob   34    Finance   80000
2          103  Charlie   29         IT   75000

In [9]:
df.tail(2)

   employee_id   name  age department  salary
4          105    Eva   24      Sales   65000
5          106  Frank   30         IT   72000

In [11]:
df.sample(frac=0.6)

   employee_id     name  age department  salary
1          102      Bob   34    Finance   80000
2          103  Charlie   29         IT   75000
5          106    Frank   30         IT   72000
3          104    David   40  Marketing   90000

In [20]:
numbers=[2,4,32,5,67]
netice=list(map(lambda x: x*3,numbers))
print(netice)

[6, 12, 96, 15, 201]

In [21]:
numbers=[2,4,32,5,67]
netice=list(filter(lambda x: x%2==0,numbers))
print(netice)

[2, 4, 32]

In [25]:
from functools import reduce
numbers=[2,4,3,5,6]
netice=reduce(lambda x,y: x*y,numbers)
print(netice)

720

In [33]:
numbers=list(range(1,10))
odd_number=list(filter(lambda x: x%2!=0, numbers))
squared_odd_num=list(map(lambda x: x**2, odd_number))
print(odd_number)
print(squared_odd_num)

[1, 3, 5, 7, 9]
[1, 9, 25, 49, 81]